---
# ==========================================
# PLAY 1: Persiapan File Laporan
# ==========================================
- name: 1. Siapkan File Laporan
  hosts: localhost
  connection: local
  gather_facts: no
  tags: setup
  tasks:
    - name: Buat Header CSV (Delimiter Pipe)
      copy:
        dest: "{{ playbook_dir }}/laporan_user_admin.csv"
        content: "Hostname|IP_Address|Inventory_Group|Username|Group_Type|Status_Akun|Estimasi_Dibuat|Terakhir_Login\n"
        force: yes

# ==========================================
# PLAY 2a: Mining Data User LINUX
# ==========================================
- name: 2a. Mining Data User Linux
  hosts: uat_centos,uat_ubuntu,uat_rhel,pro_centos,pro_centos9,pro_ubuntu,pro_rhel
  become: yes
  gather_facts: yes
  ignore_unreachable: yes
  tags: linux
  tasks:
    - name: Ambil Data User Linux
      shell: |
        if [ -f /etc/redhat-release ]; then GRP="wheel"; else GRP="sudo"; fi
        USERS=$(getent group $GRP | awk -F: '{print $4}' | tr ',' ' ')
        
        export LANG=en_US.UTF-8

        for U in $USERS; do
            [ -z "$U" ] && continue
            
            # FORMAT TANGGAL CREATED
            RAW_CREATED=$(stat -c %y /home/$U 2>/dev/null | cut -d'.' -f1)
            if [ -n "$RAW_CREATED" ]; then
                CREATED=$(date -d "$RAW_CREATED" +"%A, %d-%m-%Y, %H:%M:%S")
            else
                CREATED="System/No-Home"
            fi
            
            # FORMAT TANGGAL LAST LOGIN
            LOGIN_INFO=$(lastlog -u $U | tail -n 1)
            if echo "$LOGIN_INFO" | grep -q "Never logged in"; then
                LAST_LOGIN="Belum_Pernah"
            else
                RAW_LAST=$(echo "$LOGIN_INFO" | awk '{for(i=4;i<=NF;i++) printf $i" "; print ""}')
                LAST_LOGIN=$(date -d "$RAW_LAST" +"%A, %d-%m-%Y, %H:%M:%S" 2>/dev/null || echo "Format_Error")
            fi
            
            # STATUS AKUN
            STATUS_RAW=$(passwd -S $U 2>/dev/null | awk '{print $2}')
            case "$STATUS_RAW" in
                P|PS|U) STATUS="Enabled" ;;
                L|LK)   STATUS="Disabled/Locked" ;;
                *)      STATUS="Unknown ($STATUS_RAW)" ;;
            esac
            
            # Output pake pipe |
            echo "$U|$GRP|$STATUS|$CREATED|$LAST_LOGIN"
        done
      register: hasil_audit
      ignore_errors: yes

    - name: Append Data Linux ke CSV
      lineinfile:
        path: "{{ playbook_dir }}/laporan_user_admin.csv"
        line: "{{ inventory_hostname }}|{{ ansible_host }}|{{ group_names | reject('match', '^(all|server_.*|target_.*)$') | first | default('N/A') }}|{{ item }}"
      with_items: "{{ hasil_audit.stdout_lines | default([]) }}"
      delegate_to: localhost
      become: no
      when: hasil_audit.stdout_lines is defined

# ==========================================
# PLAY 2b: Mining Data Admin Windows
# ==========================================
- name: 2b. Mining Data Admin Windows
  hosts: uat_windows,pro_windows
  gather_facts: no
  ignore_unreachable: yes
  tags: windows
  tasks:
    - name: Ambil Data Admin Windows
      ansible.windows.win_shell: |
        {{ lookup('file', 'get_admin_data.ps1') }}
      register: win_audit_raw

    - name: Append Data Windows ke CSV
      delegate_to: localhost
      become: no
      lineinfile:
        path: "{{ playbook_dir }}/laporan_user_admin.csv"
        line: "{{ inventory_hostname }}|{{ ansible_host }}|{{ group_names | reject('match', '^(all|server_.*|target_.*)$') | first | default('N/A') }}|{{ item | trim }}"
      with_items: "{{ win_audit_raw.stdout_lines | default([]) }}"
      when:
        - win_audit_raw.stdout_lines is defined
        - "'|' in item"

# ==========================================
# PLAY 3: Sortir Data
# ==========================================
- name: 3. Rapikan & Sortir Hasil CSV
  hosts: localhost
  connection: local
  tags: sorting
  tasks:
    - name: Sortir File CSV Berdasarkan Grup
      shell: |
        head -n 1 laporan_user_admin.csv > laporan_temp.csv
        tail -n +2 laporan_user_admin.csv | sort -t'|' -k3,3 -k1,1 >> laporan_temp.csv
        mv laporan_temp.csv laporan_user_admin.csv
      args:
        chdir: "{{ playbook_dir }}"