---
- name: Smart Hardening (Auto-Detect NTP & Firewall)
  hosts: sit_ubuntu
  become: yes
  vars:
    # 1. Config Timezone
    target_timezone: "Asia/Jakarta"

    # 2. Config Swap
    swap_file_path: /swapfile
    swap_file_size_mb: 4096

    # 3. Config User & ACL
    data_admin_users:
      - "endiaz"
      - "sys-admin-eli"

    # 4. Config Ports & IPs
    allowed_ports: [22, 80, 443, 9100]

    # List IP yang diizinkan
    trusted_subnets:
      - { ip: "172.16.134.0/24", name: "Laptop Physical Network" }
      - { ip: "172.24.240.0/20", name: "Laptop WSL Network" }
      - { ip: "172.16.204.0/24", name: "Internal SIT Servers" }
      - { ip: "192.168.10.75/32", name: "Jenkins Agent" }

  tasks:
    # =======================================================
    # STEP 0: INTELLIGENCE GATHERING
    # =======================================================
    - name: Kumpulkan informasi Service yang jalan
      service_facts:

    - name: Set Timezone to Asia/Jakarta
      timezone:
        name: "{{ target_timezone }}"

    # =======================================================
    # STEP 1: SMART NTP HANDLING
    # =======================================================

    # Perhatikan tanda kutip "..." di name task di bawah ini:
    - name: "[NTP] Configure Chrony (Existing)"
      service:
        name: chrony
        state: started
        enabled: yes
      when: "'chrony.service' in services and services['chrony.service']['state'] == 'running'"
      register: chrony_status

    - name: "[NTP] Configure NTP Classic (Existing)"
      service:
        name: ntp
        state: started
        enabled: yes
      when: "'ntp.service' in services and services['ntp.service']['state'] == 'running'"
      register: ntp_status

    - name: "[NTP] Fallback to systemd-timesyncd"
      block:
        - name: Unmask systemd-timesyncd
          systemd:
            name: systemd-timesyncd
            masked: no

        - name: Enable systemd-timesyncd
          systemd:
            name: systemd-timesyncd
            state: started
            enabled: yes
      when:
        - chrony_status is skipped
        - ntp_status is skipped

    # =======================================================
    # STEP 2: SWAP MEMORY
    # =======================================================
    - name: Cek Swap
      command: swapon --show
      register: swap_check
      changed_when: false

    - name: Setup Swap File (Jika belum ada)
      block:
        - command: dd if=/dev/zero of={{ swap_file_path }} bs=1M count={{ swap_file_size_mb }}
        - file: path={{ swap_file_path }} mode='0600'
        - command: mkswap {{ swap_file_path }}
        - command: swapon {{ swap_file_path }}
        - mount:
            name: none
            src: "{{ swap_file_path }}"
            fstype: swap
            opts: sw
            passno: 0
            dump: 0
            state: present
      when: swap_check.stdout == ""

    # =======================================================
    # STEP 3: ACL DATA FOLDER
    # =======================================================
    - name: Install ACL package
      apt:
        name: acl
        state: present

    - name: Pastikan /data ada
      file: path=/data state=directory mode='0775'

    - name: Set ACL Recursive (Current Files)
      acl:
        path: /data
        entity: "{{ item }}"
        etype: user
        permissions: rwx
        recursive: yes
        state: present
      loop: "{{ data_admin_users }}"
      ignore_errors: yes

    - name: Set ACL Default (Future Files)
      acl:
        path: /data
        entity: "{{ item }}"
        etype: user
        permissions: rwx
        default: yes
        state: present
      loop: "{{ data_admin_users }}"
      ignore_errors: yes

    # =======================================================
    # STEP 4: SMART FIREWALL
    # =======================================================

    - name: Cek status Firewalld
      set_fact:
        firewalld_active: "{{ 'firewalld.service' in services and services['firewalld.service']['state'] == 'running' }}"

    # --- OPSI A: Jika Firewalld Aktif ---
    - name: "[Firewall] Apply Rules via Firewalld (Existing)"
      firewalld:
        service: "{{ item }}"
        permanent: yes
        state: enabled
        immediate: yes
      loop: [http, https, ssh]
      when: firewalld_active

    - name: "[Firewall] Open Custom Ports via Firewalld"
      firewalld:
        port: "{{ item }}/tcp"
        permanent: yes
        state: enabled
        immediate: yes
      loop: "{{ allowed_ports }}"
      when: firewalld_active

    - name: "[Firewall] Trust Subnets via Firewalld"
      firewalld:
        source: "{{ item.ip }}"
        zone: trusted
        permanent: yes
        state: enabled
        immediate: yes
      loop: "{{ trusted_subnets }}"
      when: firewalld_active

    # --- OPSI B: Jika Firewalld TIDAK Aktif (Pakai UFW) ---
    - name: "[Firewall] Install UFW"
      apt: name=ufw state=present
      when: not firewalld_active

    - name: "[Firewall] Reset UFW"
      ufw: state=reset
      when: not firewalld_active

    - name: "[Firewall] Default Policy"
      ufw: default=deny direction=incoming
      when: not firewalld_active

    - name: "[Firewall] Allow Ports via UFW"
      ufw:
        rule: allow
        port: "{{ item }}"
        proto: tcp
      loop: "{{ allowed_ports }}"
      when: not firewalld_active

    - name: "[Firewall] Allow Trusted Subnets via UFW"
      ufw:
        rule: allow
        src: "{{ item.ip }}"
        comment: "{{ item.name }}"
      loop: "{{ trusted_subnets }}"
      when: not firewalld_active

    - name: "[Firewall] Enable UFW"
      ufw: state=enabled
      when: not firewalld_active