---
- name: Setup Jenkins Deployer User & Security Access
  hosts: sit_ubuntu
  become: yes
  vars:
    # Password "c1SUnwK2yVie5N7"
    jenkins_pass: !vault |
      $ANSIBLE_VAULT;1.1;AES256
      64333066653763306530333030373732653665616437316334303837303762613234656262343163
      6664643364626532353866636162633164343434313066630a376138346435666564326561666635
      37376635636538326161613264623962633530323864306533323639663438326162633534643165
      3765326266313831380a326634653137383637343634636436353836663465316532663633303638
      6361

  tasks:
    # -------------------------------------------------------
    # 1. USER & GROUP MANAGEMENT
    # -------------------------------------------------------
    - name: Ensure group 'sugroup' exists
      group:
        name: sugroup
        state: present

    - name: Create User jenkins-deployer
      user:
        name: jenkins-deployer
        # Menggunakan trim untuk buang karakter newline siluman
        password: "{{ jenkins_pass | trim | password_hash('sha512') }}"
        shell: /bin/bash
        groups: docker,sugroup
        append: yes
        state: present
        update_password: always

    - name: Set Password Age to immediate (chage)
      shell: chage -m 0 -M 99999 jenkins-deployer
      changed_when: false

    # -------------------------------------------------------
    # 2. SSH SECURITY CONFIGURATION (AllowUsers)
    # -------------------------------------------------------
    - name: Check if AllowUsers is already defined in sshd_config
      shell: grep -q "^AllowUsers" /etc/ssh/sshd_config
      register: allow_users_check
      failed_when: false
      changed_when: false

    - name: Add jenkins-deployer to existing AllowUsers line
      replace:
        path: /etc/ssh/sshd_config
        regexp: '^(AllowUsers(?!.*\bjenkins-deployer\b).*)$'
        replace: '\1 jenkins-deployer'
      when: allow_users_check.rc == 0
      notify: Restart SSH

    - name: Create AllowUsers line if not exists
      lineinfile:
        path: /etc/ssh/sshd_config
        line: 'AllowUsers sys-admin-eli endiaz thomas jenkins-deployer'
        state: present
      when: allow_users_check.rc != 0
      notify: Restart SSH

    # -------------------------------------------------------
    # 3. DIRECTORY & ACL PERMISSION
    # -------------------------------------------------------
    - name: Ensure /data directory exists
      file:
        path: /data
        state: directory
        owner: root
        group: docker
        mode: '0775'

    - name: Set ACL permissions for jenkins-deployer on /data
      acl:
        path: /data
        entity: jenkins-deployer
        etype: user
        permissions: rwx
        state: present
        recursive: yes

    - name: Set Default ACL for future files
      acl:
        path: /data
        entity: jenkins-deployer
        etype: user
        permissions: rwx
        state: present
        default: yes

    - name: Create Ansible temporary directory for jenkins-deployer
      file:
        path: /home/jenkins-deployer/.ansible/tmp
        state: directory
        owner: jenkins-deployer
        group: jenkins-deployer
        mode: '0755' # Gunakan 0755 agar lebih fleksibel dibanding 0700

  handlers:
    - name: Restart SSH
      service:
        name: ssh
        state: restarted