---
- name: Install and Configure Wazuh Agent (With Manual Auth)
  hosts: sit_ubuntu
  become: yes
  vars:
    wazuh_manager_ip: "172.16.203.18"
    wazuh_deb_url: "https://packages.wazuh.com/4.x/apt/pool/main/w/wazuh-agent/wazuh-agent_4.14.3-1_amd64.deb"
    download_path: "/data/wazuh-agent"

  tasks:
    # -------------------------------------------------------
    # 1. PREPARASI & DOWNLOAD
    # -------------------------------------------------------
    - name: Create download directory
      file: path="{{ download_path }}" state=directory mode='0755'

    - name: Download Wazuh Agent package
      get_url: { url: "{{ wazuh_deb_url }}", dest: "{{ download_path }}/wazuh-agent.deb" }

    # -------------------------------------------------------
    # 2. INSTALASI
    # -------------------------------------------------------
    - name: Install Wazuh Agent
      shell: "WAZUH_MANAGER='{{ wazuh_manager_ip }}' dpkg -i {{ download_path }}/wazuh-agent.deb"

    # -------------------------------------------------------
    # 3. MANUAL REGISTRATION (Penting buat IN101)
    # -------------------------------------------------------
    - name: Check if agent is already registered
      stat: path=/var/ossec/etc/client.keys
      register: wazuh_keys

    - name: Register Agent via agent-auth
      shell: "/var/ossec/bin/agent-auth -m {{ wazuh_manager_ip }} -A {{ inventory_hostname }}"
      # Jalankan cuma kalau file key belum ada (belum regis)
      when: not wazuh_keys.stat.exists or wazuh_keys.stat.size == 0
      notify: Restart Wazuh Agent

    # -------------------------------------------------------
    # 4. KONFIGURASI OSSEC.CONF
    # -------------------------------------------------------
    - name: Configure ossec.conf
      copy:
        dest: /var/ossec/etc/ossec.conf
        owner: root
        group: wazuh
        mode: '0660'
        content: |
          <ossec_config>
            <client>
              <server><address>{{ wazuh_manager_ip }}</address></server>
              <auto_restart>yes</auto_restart>
            </client>
            <wodle name="docker-listener">
              <disabled>no</disabled>
            </wodle>
            <logging><log_format>plain</log_format></logging>
          </ossec_config>
      notify: Restart Wazuh Agent

  handlers:
    - name: Restart Wazuh Agent
      service: name=wazuh-agent state=restarted